- Gemfile.lock
- app/models/ride.rb
- db/migrate/20221121155133_create_rides.rb
- test/models/ride_test.rb
Nous avons créé le model rides avec les belongs to et has many, ainsi que les validations qui nous paraissaient nécessaires.
A vous de juger :)
> ride model with validations

- Gemfile.lock
- app/models/booking.rb
- db/migrate/20221121161019_create_bookings.rb
- test/models/booking_test.rb
nous avons créé le model 'booking' avec des validations
> booking model with validations

- Gemfile.lock
- app/controllers/bookings_controller.rb
- test/controllers/bookings_controller_test.rb
nous avons créé le booking controller
> booking controller created

- config/routes.rb
nous avons créé les routes pour rides (tout le crud), et booking pour create and new.
pour pages, on a bien le home, mais il manque le dashboard qu'il faudra créer.
> coded routes for rides and booking but missing pages dashboard

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/policies/application_policy.rb
- app/policies/restaurant_policy.rb
- test/policies/restaurant_policy_test.rb
authorization set up (rien changé dedans)
> authorization done

- Gemfile
- Gemfile.lock
- app/models/ride.rb
- db/seeds.rb
seed creation : 3 x users & 10 x rides
> seed creation

- app/controllers/bookings_controller.rb
- app/views/bookings/new.html.erb
Creation des méthodes du controller mais nous n'avons pas pu le tester car il manquait la seed
> Booking c with view

- app/controllers/rides_controller.rb
- app/policies/restaurant_policy.rb
- app/policies/ride_policy.rb
- app/views/rides/index.html.erb
- app/views/rides/new.html.erb
- app/views/rides/show.html.erb
- db/migrate/20221121155133_create_rides.rb
- db/seeds.rb
nous avons fait les modif nécessaires pour autoriser :
- tous les users à accéder à l'index, aux show, au new/create du controller rides
- chaque user peut edit/update/destroy
Nous avons également modifier la seed pour qu'elle fonctionne
Afin que tous les test puissent être réaliser nous avons fait quelques modifications sur les views du controller rides
> authorization + controller rides + seeds pour verification

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_booking.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/bookings/new.html.erb
- app/views/rides/index.html.erb
- app/views/shared/_navbar.html.erb
> Booking nav

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
Home
Placehoders texts and icons to be changed at next commit
> home work in progress

- app/assets/stylesheets/pages/_show.scss
- app/views/rides/show.html.erb
ajout boutons sur la show details, a voir comment supprimer la puce
> boutons show

- app/assets/stylesheets/pages/_show.scss
- db/schema.rb
> show marks and footer sticky

- app/views/pages/dashboard.html.erb
> new dashboard

- app/models/ride.rb
- db/seeds.rb
I have completed the seeds.
There are 30 seeds in total (10 for each category) with real addresses so we can also test ucpoming geocoding map.
Can someone have a look at the syntax (I donot remember if each instance needs to be in an array of ash).
> seeds complete 30 in total

- app/assets/stylesheets/pages/_show.scss
- app/views/rides/show.html.erb
j'ai amélioré l'aspect de la page
pictos, gras sur les titres
bouton plus gros 
et boutons annexes plus discrets
> front show boutons texte et pictos

- app/views/rides/show.html.erb
- app/views/shared/_navbar.html.erb
conditions pour que les boutons s'affichent en fonction de qui est connecté (possibilité de booker quand c'est pas un ride à soi ou possibilité d'éditer et destroy lorsque c'est un ride à soi, et inversement)
affichage de l'username dans la navbar, mais log out à revoir
> conditions buttons

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
Centered elements + reverted button to make it visible
> continuing-home

- app/assets/stylesheets/application.scss
- app/controllers/bookings_controller.rb
- app/controllers/pages_controller.rb
- app/policies/booking_policy.rb
- app/views/bookings/show.html.erb
- app/views/pages/dashboard.html.erb
- config/routes.rb
created booking show
modify dashboard with request + notif on my bookings
> booking show ok and dashboard notif ok need to edit booking

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/pages/_indexrides.scss
- app/controllers/rides_controller.rb
- app/javascript/controllers/index.js
- app/javascript/controllers/map_controller.js
- app/models/ride.rb
- app/views/layouts/application.html.erb
- app/views/rides/index.html.erb
- config/initializers/geocoder.rb
- db/migrate/20221124093202_add_coordinates_to_rides.rb
- db/schema.rb
Added the map with geocoder gem on the index so far without pimped styles
> added geocoding feature

- .gitignore
> .env de william

- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_form.scss
- app/assets/stylesheets/pages/_new.scss
- app/views/rides/_form.html.erb
- app/views/rides/edit.html.erb
- app/views/rides/new.html.erb
form pour éditer
uniformisation des forms du site (shadow)
> edit form front and uniformization of forms

- db/migrate/20221124162618_add_image_to_user.rb
- db/seeds.rb
> add column

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
Finished footer polish
Aligned all elements  of the homepage in container
Added card with same style than other cards
> finished polish on footer

- app/assets/stylesheets/application.scss
- db/schema.rb
Added top-margin on the wrapper so nav bar does not hide anymore top page content
> added margin-top to wrapper to fix nav bar

- db/migrate/20221125095857_add_pic_to_rides.rb
- db/schema.rb
I have updated the model adding the column photo to Rides model
> added column photo to Rides

- app/assets/stylesheets/pages/_dashboard.scss
- app/views/rides/show.html.erb
- db/schema.rb
> front show again apres cata
